=begin pod

=head1 NAME

B<GNU::Time> - Provides an easy interface for the GNU C<time> command on Linux and OSX hosts.

NOTE: This module replaces the time-related routines in module B<Proc::More> (which is now
deprecated).

=head1 SYNOPSIS

=begin code :lang<raku>
use GNU::Time;
say time-command "locate lib"; # OUTPUT 0.260
=end code

=head1 DESCRIPTION

B<GNU::Time> provides the C<time-command> subroutine for easy access
to the GNU C<time> command on Linux and OSX hosts.

=head2 sub time-command

Purpose : Collect the process times for a system or user command (using the GNU C<time> command).
Runs the input command using the system C<run> function and returns
the process times shown below.

=begin code :lang<raku>
sub time-command(Str:D $cmd,
                 :$typ where { $typ ~~ &typ } = 'u',            
                 :$fmt where { !$fmt.defined || $fmt ~~ &fmt }, 
		 :$dir,
                 Bool :$list = False,
                ) is export {...}
=end code


=head3 Parameters:

=item C<$cmd> - The command as a string.
Note special characters are not recognized by Raku's C<run> routine, 
so results may not be as expected if they are part of the command.

=item C<:$typ> - Type of time values to return 
(see token C<typ> definition)

=item C<:$fmt> - Desired format of returned time values
(see token C<fmt> definition)

=item C<:$dir> - Directory in which to execute the command
=item C<:$list> - Return the time values as a list

=head3 The C<typ> and C<fmt> tokens:

=begin code :lang<raku>
my token typ { ^ :i        
    # the desired time(s) to return:
    a|all|   # show all times in desired format
    r|real|  # show real (wall clock) time
    u|user|  # show the user time [default]
    s|sys    # show the system time
$ }

my token fmt { ^ :i        
    # the desired format for the time(s) 
                # [default: raw seconds]
    s|seconds|  # time in seconds with an appended 
                #   's': "30.42s"
    h|hms|      # time in hms format: "0h00m30.42s"
    ':'|'h:m:s' # time in h:m:s format: "0:00:30.42"
$ }
=end code

=head3 Returns:

A string consisting in one or all of real (wall clock), user, and
 system times (in one of four formats), or a list as in the original API.

=head1 AUTHOR

Tom Browder <tbrowder@cpan.org>

=head1 COPYRIGHT and LICENSE

Copyright © 2021 Tom Browder

This library is free software; you may redistribute or modify it under the Artistic License 2.0.

=end pod
